const Background = [
  "layers/Background/Atomic Tangerine.png",
  "layers/Background/Desert Sand Fade.png",
  "layers/Background/Light Moss Fade.png",
  "layers/Background/Marshmallow Cream.png",
  "layers/Background/Opal Fade.png",
  "layers/Background/Pale Cerulean Fade.png",
  "layers/Background/Pastel Melon Fade.png",
  "layers/Background/Pastel Pink Fade.png",
  "layers/Background/Pink Pearl Fade.png",
  "layers/Background/Wild Blue Yonder.png",
];

const Avatar = [
  "layers/Avatar/Android.png",
  "layers/Avatar/Aquarian Ceil.png",
  "layers/Avatar/Aquarian Green.png",
  "layers/Avatar/Aquarian Peach.png",
  "layers/Avatar/Aquarian Purple.png",
  "layers/Avatar/Celestial.png",
  "layers/Avatar/Dr. Frank's Monster.png",
  "layers/Avatar/Psychonaut.png",
  "layers/Avatar/Reptilian.png",
  "layers/Avatar/Shaggarian.png",
  "layers/Avatar/Spacian Albino.png",
  "layers/Avatar/Spacian Ceil.png",
  "layers/Avatar/Spacian Green.png",
  "layers/Avatar/Spacian Opal.png",
  "layers/Avatar/Spacian Purple.png",
  "layers/Avatar/Transparian Spring Green.png",
  "layers/Avatar/Transparian Turquoise Surf.png",
];

const Clothes = [
  "layers/Clothes/Naked",
  "layers/Clothes/Amarillo.png",
  "layers/Clothes/Astronaut.png",
  "layers/Clothes/Banana.png",
  "layers/Clothes/Bathrobe.png",
  "layers/Clothes/Biggie's Other Sweater.png",
  "layers/Clothes/Biggie's Sweater.png",
  "layers/Clothes/Black Tee.png",
  "layers/Clothes/Bowie.png",
  "layers/Clothes/Coconut Bra.png",
  "layers/Clothes/Cool School.png",
  "layers/Clothes/Disco Gold.png",
  "layers/Clothes/Disco Silver.png",
  "layers/Clothes/Earth Tee and Backpack.png",
  "layers/Clothes/Earth Tee.png",
  "layers/Clothes/Elvis.png",
  "layers/Clothes/Flannel.png",
  "layers/Clothes/Naked",
  "layers/Clothes/Freddy's Tanktop.png",
  "layers/Clothes/Golf Sweater.png",
  "layers/Clothes/Hawaiian Blue.png",
  "layers/Clothes/Hawaiian Classic.png",
  "layers/Clothes/Hawaiian Purple.png",
  "layers/Clothes/Hawaiian Red.png",
  "layers/Clothes/Hawaiian Yellow.png",
  "layers/Clothes/Hippie.png",
  "layers/Clothes/Interstellar.png",
  "layers/Clothes/Jean Jacket.png",
  "layers/Clothes/Kimono.png",
  "layers/Clothes/Lei.png",
  "layers/Clothes/Leopard.png",
  "layers/Clothes/Lifevest.png",
  "layers/Clothes/One Eyed Jack.png",
  "layers/Clothes/Overalls.png",
  "layers/Clothes/Pharaoh.png",
  "layers/Clothes/Pilot.png",
  "layers/Clothes/Poncho.png",
  "layers/Clothes/Prisoner.png",
  "layers/Clothes/Rainbow Jacket.png",
  "layers/Clothes/Rainjacket Blue.png",
  "layers/Clothes/Sailor.png",
  "layers/Clothes/Naked",
  "layers/Clothes/Saturn Suit.png",
  "layers/Clothes/Sgt. Paul.png",
  "layers/Clothes/Sgt. Ringo.png",
  "layers/Clothes/Sheriff's Vest and Bandana.png",
  "layers/Clothes/Tanktop Black.png",
  "layers/Clothes/The Rock.png",
  "layers/Clothes/Thriller.png",
  "layers/Clothes/Tinman.png",
  "layers/Clothes/Tribal.png",
  "layers/Clothes/Turtleneck Purple.png",
  "layers/Clothes/Turtleneck White and Overalls.png",
  "layers/Clothes/Turtleneck White.png",
  "layers/Clothes/Turtleneck Yellow and Overalls.png",
  "layers/Clothes/Tux.png",
  "layers/Clothes/Viking.png",
  "layers/Clothes/White Tee and Overalls.png",
  "layers/Clothes/White Tee.png",
  "layers/Clothes/Zoo Animals.png",
  "layers/Clothes/Naked",
];

const Eyes = [
  "layers/Eyes/3D Glasses.png",
  "layers/Eyes/Angry Eyes.png",
  "layers/Eyes/Aviators.png",
  "layers/Eyes/Bitcoin Eyes.png",
  "layers/Eyes/Black Eyes.png",
  "layers/Eyes/Blue Cyclops.png",
  "layers/Eyes/Blue Galaxy Eyes.png",
  "layers/Eyes/Blue Lazer Eyes.png",
  "layers/Eyes/Blue Lennon Glasses.png",
  "layers/Eyes/Blue Metal.png",
  "layers/Eyes/Broken Computer.png",
  "layers/Eyes/Commander Visor.png",
  "layers/Eyes/Confused Eyes.png",
  "layers/Eyes/Cyber Visor.png",
  "layers/Eyes/Elvis Glasses.png",
  "layers/Eyes/Eye Patch.png",
  "layers/Eyes/Goth Eyes.png",
  "layers/Eyes/Green Computer.png",
  "layers/Eyes/Green Terminator.png",
  "layers/Eyes/Leopard Glasses.png",
  "layers/Eyes/Light Blue Eyes.png",
  "layers/Eyes/Love Eyes.png",
  "layers/Eyes/Monocle.png",
  "layers/Eyes/Orange Lennon Glasses.png",
  "layers/Eyes/Pink Eyes.png",
  "layers/Eyes/Purple Computer.png",
  "layers/Eyes/Purple Cyclops.png",
  "layers/Eyes/Purple Eyes.png",
  "layers/Eyes/Purple Galaxy Eyes.png",
  "layers/Eyes/Rainbow Lazer Eyes.png",
  "layers/Eyes/Reading Glasses.png",
  "layers/Eyes/Red Computer.png",
  "layers/Eyes/Red Cyclops.png",
  "layers/Eyes/Red Lazer Eyes.png",
  "layers/Eyes/Red Terminator.png",
  "layers/Eyes/Scar Eyes.png",
  "layers/Eyes/Shocked Eyes.png",
  "layers/Eyes/Stoned Eyes.png",
  "layers/Eyes/Subtle Goth Eyes.png",
  "layers/Eyes/Swollen Eye.png",
  "layers/Eyes/Tired Eyes.png",
  "layers/Eyes/VR Goggles.png",
  "layers/Eyes/Verified Glasses.png",
  "layers/Eyes/Visor.png",
  "layers/Eyes/Wacked Eyes.png",
];

const Mouth = [
  "layers/Mouth/Angry.png",
  "layers/Mouth/Biting Bitcoin.png",
  "layers/Mouth/Biting Lip.png",
  "layers/Mouth/Blowing Bubble Gum.png",
  "layers/Mouth/Braces.png",
  "layers/Mouth/Cigar.png",
  "layers/Mouth/Cookie.png",
  "layers/Mouth/Donut.png",
  "layers/Mouth/Elated.png",
  "layers/Mouth/Gas Mask.png",
  "layers/Mouth/Gold Teeth.png",
  "layers/Mouth/Growling.png",
  "layers/Mouth/Half Grin.png",
  "layers/Mouth/Knife.png",
  "layers/Mouth/Metal Mask Peach.png",
  "layers/Mouth/Metal Mask Purple.png",
  "layers/Mouth/Metal Mask Silver.png",
  "layers/Mouth/Missing Tooth.png",
  "layers/Mouth/Mr. Mercury.png",
  "layers/Mouth/Mustache With Pipe.png",
  "layers/Mouth/Mustache.png",
  "layers/Mouth/Nonchalant.png",
  "layers/Mouth/Purple Lips.png",
  "layers/Mouth/Romantic.png",
  "layers/Mouth/Simple Pipe.png",
  "layers/Mouth/Smirk.png",
  "layers/Mouth/Smoke Ring Strong.png",
  "layers/Mouth/Smoke Ring.png",
  "layers/Mouth/Starfish.png",
  "layers/Mouth/Taped.png",
  "layers/Mouth/Tongue Out.png",
  "layers/Mouth/Wheat Stalk.png",
];

const Headwear = [
  "layers/Headwear/Ace Hair.png",
  "layers/Headwear/Afro.png",
  "layers/Headwear/Airtraffic Controller.png",
  "layers/Headwear/Bandana.png",
  "layers/Headwear/Beer Cap.png",
  "layers/Headwear/Black Beanie.png",
  "layers/Headwear/Blue Earth Hat.png",
  "layers/Headwear/Captain.png",
  "layers/Headwear/Cerebral Case.png",
  "layers/Headwear/Cerebral Helm.png",
  "layers/Headwear/Coral Crown.png",
  "layers/Headwear/Cowboy Hat.png",
  "layers/Headwear/Drizzle Dome.png",
  "layers/Headwear/Elvis Hair.png",
  "layers/Headwear/Explorer.png",
  "layers/Headwear/Floppy Hat.png",
  "layers/Headwear/Fruit Hat.png",
  "layers/Headwear/Gas Mask.png",
  "layers/Headwear/Green Earth Hat.png",
  "layers/Headwear/Hacker Headgear.png",
  "layers/Headwear/Headphones.png",
  "layers/Headwear/Maroon Beanie.png",
  "layers/Headwear/Mickey Hat.png",
  "layers/Headwear/Mohawk.png",
  "layers/Headwear/NeuroLink Cap.png",
  "layers/Headwear/Pink Earth Cap.png",
  "layers/Headwear/Pirate Hat.png",
  "layers/Headwear/Poker Hat.png",
  "layers/Headwear/Purple Bowie.png",
  "layers/Headwear/Red Bowie.png",
  "layers/Headwear/RoboCop.png",
  "layers/Headwear/Sailor Hat.png",
  "layers/Headwear/Scottish Bonnet.png",
  "layers/Headwear/Tin Hat.png",
  "layers/Headwear/Umbrella Hat.png",
  "layers/Headwear/Viking Helm.png",
  "layers/Headwear/White Cowboy Hat.png",
  "layers/Headwear/Yellow Beanie.png",
];

const layers = [Background, Avatar, Clothes, Eyes, Mouth, Headwear];

window.$layers = layers;
